version: "3.5"

volumes:
  data:

services:
  memberchannels:
    image: purplg/memberchannels:latest
    container_name: "memberchannels"
    env_file: .env
    volumes:
      - data:/dist/db
    restart: unless-stopped
